package com.example.coffeebookingapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF324A59)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF476374)
val md_theme_light_onPrimaryContainer = Color(0xFFCED6DB)
val md_theme_light_secondary = Color(0xFF324A59)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF476374)
val md_theme_light_onSecondaryContainer = Color(0xFFCED6DB)
val md_theme_light_tertiary = Color(0xFF324A59)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF476374)
val md_theme_light_onTertiaryContainer = Color(0xFFCED6DB)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFE5E5)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFFF3030)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF324A59)
val md_theme_light_surface = Color(0xFFF7F8FB)
val md_theme_light_onSurface = Color(0xFF001833)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF324A59)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF7FD0FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00658C)
val md_theme_light_outlineVariant = Color(0xFFEFEFEF)
val md_theme_light_scrim = Color(0xFF000000)

val light_onPrimary2 = Color(0xFFD8D8D8)
val light_onBackground2 = Color(0xFF99A5AC)
val light_onSurface2 = Color(0xFF757575)
val light_darkPrimary = Color(0xFF001833)
val light_inactive = Color(0xFFD8D8D8)

val md_theme_dark_primary = Color(0xFF7FD0FF)
val md_theme_dark_onPrimary = Color(0xFF00344A)
val md_theme_dark_primaryContainer = Color(0xFF004C6A)
val md_theme_dark_onPrimaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_secondary = Color(0xFF7FD0FF)
val md_theme_dark_onSecondary = Color(0xFF00344A)
val md_theme_dark_secondaryContainer = Color(0xFF004C6A)
val md_theme_dark_onSecondaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_tertiary = Color(0xFF7FD0FF)
val md_theme_dark_onTertiary = Color(0xFF00344A)
val md_theme_dark_tertiaryContainer = Color(0xFF004C6A)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9297)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF00658C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7FD0FF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF324A59)
